# Generated by Django 3.1.14 on 2023-07-05 15:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200, null=True)),
                ('title_jp', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('appeared_at', models.DateTimeField(default=datetime.datetime(2023, 7, 5, 18, 5, 32, 292732))),
                ('disappeared_at', models.DateTimeField(default=datetime.datetime(2023, 7, 5, 18, 5, 32, 292732))),
                ('level', models.IntegerField(default=1)),
                ('health', models.IntegerField(default=100)),
                ('strength', models.IntegerField(default=100)),
                ('defence', models.IntegerField(default=100)),
                ('stamina', models.IntegerField(default=100)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon', to='pokemon_entities.pokemon')),
            ],
        ),
    ]
